version: "3"
services:

  postgres:
    image: onjin/alpine-postgres:9.5
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_USER: goddd
      POSTGRES_PASSWORD: goddd
      POSTGRES_DB: goddd

  # Database migration service
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://postgres:5432/goddd -schemas=goddd -user=goddd -password=goddd -connectRetries=60 migrate
    volumes:
      - ./migrations/:/flyway/sql
    links:
      - postgres
    depends_on:
      - postgres

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    expose:
      - "2181"

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test-topic:1:1"